In [1]:
import ScraperFC as sfc

In [2]:
# Scrape 2018-19 EPL goal and shot creation from FBRef
try:
    scraper = sfc.FBRef()
    df = scraper.scrape_goal_shot_creation(2019, "EPL")
    scraper.close()
except:
    print("Scraping failed :(")
    scraper.close()
df # df is an array. First element is "for" stats. Second is "against" stats

(   Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0   SCA SCA Types  \
                 Squad               # Pl                90s   SCA  PassLive
 0             Arsenal                 28               38.0   773       609
 1         Bournemouth                 28               38.0   669       484
 2            Brighton                 21               38.0   590       397
 3             Burnley                 23               38.0   528       346
 4        Cardiff City                 25               38.0   574       376
 5             Chelsea                 24               38.0  1018       801
 6      Crystal Palace                 26               38.0   779       542
 7             Everton                 23               38.0   739       486
 8              Fulham                 28               38.0   712       540
 9        Huddersfield                 31               38.0   589       415
 10     Leicester City                 25               38.0   779       544
 11          Liverpool                 23               38.0   912       667
 12    Manchester City                 21               38.0  1093       833
 13     Manchester Utd                 28               38.0   854       642
 14      Newcastle Utd                 24               38.0   633       454
 15        Southampton                 30               38.0   725       496
 16          Tottenham                 28               38.0   844       603
 17            Watford                 25               38.0   651       465
 18           West Ham                 26               38.0   683       478
 19             Wolves                 21               38.0   702       516

                               GCA GCA Types
    PassDead Drib  Sh Fld Def  GCA  PassLive PassDead Drib  Sh Fld Def OG
 0        46   47  31  22  15  122        95        6    5   5   7   1  3
 1        63   40  28  43  10   98        64        7    7   6  10   3  1
 2        77   34  34  40   8   55        29        9    2   7   7   1  0
 3        79   17  39  38   7   67        42       10    1   9   2   1  2
 4        77   35  40  37   8   52        35        4    3   7   2   0  1
 5        57   55  39  52  13  115        81        7   10   7   8   1  1
 6        68   63  46  44  13   90        51        6    6   8  13   3  3
 7        83   52  51  51  15   82        55        4   10   9   2   1  1
 8        58   48  37  20   8   61        42        3    7   5   3   0  1
 9        66   24  30  32  20   35        23        5    0   2   2   1  2
 10       75   52  43  42  22   84        56        2    8   6   9   2  1
 11       69   70  46  38  19  146        99        9   11  10  11   3  3
 12       68   76  57  41  15  164       128        6   10   5   9   3  3
 13       54   53  40  50  15  112        75        4   11  10  10   2  0
 14       61   39  28  32  18   61        43        5    0   8   2   2  1
 15       66   45  50  46  21   69        49        0    3   5   7   4  1
 16       72   61  47  43  18  103        68        8    8  11   8   0  0
 17       53   44  30  41  17   83        53        8   12   4   3   2  1
 18       75   31  45  36  17   82        54        6    4   9   7   1  1
 19       60   40  38  33  14   82        58        6    3   6   8   0  1  ,
     Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0   SCA SCA Types  \
                  Squad               # Pl                90s   SCA  PassLive
 0           vs Arsenal                 28               38.0   771       546
 1       vs Bournemouth                 28               38.0   815       631
 2          vs Brighton                 21               38.0   894       633
 3           vs Burnley                 23               38.0  1046       825
 4      vs Cardiff City                 25               38.0   901       639
 5           vs Chelsea                 24               38.0   525       378
 6    vs Crystal Palace                 26               38.0   813       588
 7           vs Everton                 23               38.0   622       428
 8            vs Fulham                 28               38.0   886       646
 9      vs Huddersfield                 31               38.0   866       627
 10   vs Leicester City                 25               38.0   637       453
 11        vs Liverpool                 23               38.0   456       338
 12  vs Manchester City                 21               38.0   368       264
 13   vs Manchester Utd                 28               38.0   778       555
 14    vs Newcastle Utd                 24               38.0   750       502
 15      vs Southampton                 30               38.0   782       561
 16        vs Tottenham                 28               38.0   709       508
 17          vs Watford                 25               38.0   732       511
 18         vs West Ham                 26               38.0   815       586
 19           vs Wolves                 21               38.0   681       475

                               GCA GCA Types
    PassDead Drib  Sh Fld Def  GCA  PassLive PassDead Drib  Sh Fld Def OG
 0        68   44  47  47  17   91        56        4    9   5  11   4  2
 1        56   33  46  35  11  121        91        3    7   9   8   0  3
 2        77   67  51  56  10  102        65        3   13  10  11   0  0
 3        66   46  68  30   7  106        79        4    5   9   5   0  4
 4        83   69  47  48  15  119        82        6   13   7   7   4  0
 5        55   34  20  20  18   62        44        7    4   4   3   0  0
 6        79   45  45  43  12   80        56        5    6   5   7   0  1
 7        64   33  36  43  16   70        42        4    2  11   7   2  2
 8        66   45  54  48  25  129        94        6    8  12   5   2  2
 9        71   60  46  49  13  134        91        8   13   6  13   3  0
 10       65   37  33  31  18   79        55        6    8   5   4   1  0
 11       38   33  17  18  12   33        25        2    0   5   0   1  0
 12       34   26  13  21  10   37        21        5    0   4   5   2  0
 13       78   51  29  46  16   94        64        9    6   4   7   1  3
 14       88   42  46  56  16   77        48        7    3   9   9   1  0
 15       77   45  43  33  20  102        67        8    6  11   2   5  3
 16       64   40  42  36  16   64        44        5    3   4   5   0  3
 17       75   54  42  34  14   89        58        5    5   9   7   3  2
 18       67   65  38  44  15  100        71       10    7   5   6   1  0
 19       56   57  36  43  12   74        47        8    3   5   8   1  2  )

In [3]:
# Scrape 2019-20 Ligue 1 table from Understat
try:
    scraper = sfc.Understat()
    df = scraper.scrape_league_table(2020, "Ligue 1")
    scraper.close()
except:
    print("Scraping failed :(")
    scraper.close()
df

,Team,M,W,D,L,G,GA,PTS,xG,NPxG,xGA,NPxGA,NPxGD,PPDA,OPPDA,DC,ODC,xPTS
0,Paris Saint Germain,27,22,2,3,75,24,68,76.42,70.34,22.43,22.43,47.90,6.88,18.38,324,100,65.68
1,Marseille,28,16,8,4,41,29,56,36.42,31.86,32.05,28.25,3.62,8.56,11.77,145,86,41.73
2,Rennes,28,15,5,8,38,24,50,34.37,30.43,28.15,24.35,6.08,10.63,10.00,121,132,41.18
3,Lille,28,15,4,9,35,27,49,40.81,34.61,30.17,25.61,9.01,9.52,12.94,141,124,47.12
4,Reims,28,10,11,7,26,21,41,28.93,25.13,26.47,21.67,3.46,12.07,9.88,131,109,40.42
5,Nice,28,11,8,9,41,38,41,36.45,32.65,42.69,37.37,-4.72,11.01,12.30,110,170,35.62
6,Lyon,28,11,7,10,42,27,40,36.24,31.68,24.73,22.45,9.24,9.89,14.16,152,121,46.34
7,Montpellier,28,11,7,10,35,34,40,34.95,31.15,32.26,28.46,2.69,10.28,10.10,119,141,40.05
8,Monaco,28,11,7,10,44,44,40,48.55,45.51,41.06,36.50,9.01,10.60,11.85,211,119,42.47
9,Angers,28,11,6,11,28,33,39,27.1,26.34,28.15,25.87,0.48,16.40,10.37,132,117,37.49
10,Strasbourg,27,11,5,11,32,32,38,34.56,31.52,33.46,28.14,3.37,11.25,10.75,133,100,37.74
11,Bordeaux,28,9,10,9,40,34,37,30.47,28.95,35.2,32.92,-3.97,9.49,11.65,91,156,37.06
12,Nantes,28,11,4,13,28,31,37,27.81,26.29,30.26,25.57,0.73,11.92,9.98,110,122,35.91
13,Brest,28,8,10,10,34,37,34,30.05,26.25,44.11,39.55,-13.30,11.36,11.57,149,154,30.64
14,Metz,28,8,10,10,27,35,34,24.65,21.61,36.54,33.50,-11.89,13.82,8.85,92,145,29.04
15,Dijon,28,7,9,12,27,37,30,27.38,26.62,39.3,38.54,-11.92,12.28,8.81,111,176,31.19
16,Saint-Etienne,28,8,6,14,29,45,30,29.65,25.85,37.73,33.17,-7.31,10.22,9.97,93,133,32.68
17,Nimes,28,7,6,15,29,44,27,30.19,28.67,40.47,37.43,-8.76,10.47,8.14,109,159,32.69
18,Amiens,28,4,11,13,31,50,23,25.62,21.69,38.43,37.67,-15.97,11.55,9.25,101,148,32.84
19,Toulouse,28,3,4,21,22,58,13,31.29,26.73,48.28,44.47,-17.74,12.78,9.34,115,178,28.01

In [4]:
# Scrape 2016-17 Serie A match logs from FiveThirtyEight
try:
    scraper = sfc.FiveThirtyEight()
    df = scraper.scrape_matches(2017, "Serie A")
    scraper.close()
except:
    print("Scraping failed :(")
    scraper.close()
df

,Date,Home Team,Away Team,Home Goals,Away Goals,FTE Home xG,FTE Away xG,FTE Home nsxG,FTE Away nsxG,Home Adj Score,Away Adj Score
0,2016-08-20,AS Roma,Udinese,4.0,0.0,6.12,0.59,2.79,1.15,3.40,0.00
1,2016-08-20,Juventus,Fiorentina,2.0,1.0,1.53,0.23,1.81,0.69,2.10,1.05
2,2016-08-21,AC Milan,Torino,3.0,2.0,2.54,1.73,1.01,2.58,3.15,2.10
3,2016-08-21,Atalanta,Lazio,3.0,4.0,1.77,1.82,2.21,0.58,3.15,3.72
4,2016-08-21,Palermo,Sassuolo,0.0,1.0,0.34,1.78,1.12,2.10,0.00,1.05
...,...,...,...,...,...,...,...,...,...,...,...
375,2017-05-28,Fiorentina,US Pescara,2.0,2.0,2.27,1.70,1.71,2.90,2.10,2.10
376,2017-05-28,Crotone,Lazio,3.0,1.0,0.90,1.14,0.88,0.82,3.15,1.05
377,2017-05-28,Internazionale,Udinese,5.0,2.0,3.11,2.78,1.81,1.75,5.05,2.10
378,2017-05-28,Torino,Sassuolo,5.0,3.0,2.23,3.35,1.41,2.20,5.02,3.15
379,2017-05-28,Palermo,Empoli,2.0,1.0,0.88,2.19,0.64,1.80,1.75,1.05